# An example recipe that shows the creation of a user role.
name: 'Wunder next setup'
description: "Enable needed modules to use next-drupal and add pathauto setup"
type: 'Setup'
recipes:
  - wunder_landing_pages
  - wunder_search
install:
  - next
  - next_jsonapi
  - pathauto
  - wunder_next
  - jsonapi_menu_items
